### ISSUE TITLE
Unnecessary high debug level for a message

### ISSUE THREAD

**Issue by mikrosk** [czietz/picowifi#1]
### What happened?

https://github.com/freemint/freemint/blob/master/sys/sockets/xif/picowifi.c#L192 has `ALERT` as a way to inform user that the PicoWifi's credentials are going to be used. However this is pretty annoying as user has to click on the OK button every single time:

![image](https://user-images.githubusercontent.com/3062260/192035544-a8624c35-b90d-4f09-b240-fa40392b1e95.png)

Also, as you can see, the CR/LF char is part of the message.

Apart from that, the device worked nicely on my Falcon030+NetUSBee+PicoWifi however I got serious stability issues on CT60 - sometimes FreeMiNT would just freeze before the alert, sometimes just before the text was rendered in the dialog and sometimes even after the text was rendered. I got maybe like 25% success rate (if the init phase works, then it seems to work reliably).

When I switch to the ASIX driver (and device), it works OK (I tried two power cycles in a row).

I can create a separate bug report if you like.

### Firmware version

ca222eb

### Software versions on the Atari

FreeMiNT snapshot from 6.8.2022 + picowifi.xif from the package.

### Hardware

Falcon 030, CT60e, NetUSBee, PicoWifi/ASIX.

**Comment by czietz** [comment]
Thank you for the report. I can "downgrade" the level to DEBUG in the
driver.

I wonder, though: If you store the Wifi credentials on the Atari in a
WIFICRED.CFG, as described in
https://github.com/czietz/picowifi/#storing-the-credentials-on-the-atari
instead of inside the PicoWifi, the alert/message won't appear. Does it
work reliably on your CT60 in that case?

**Comment by mikrosk** [comment]
Ok, so with WIFICRED.CFG it seems to be working _much_ better (although I don't fancy yet another `ALERT` telling me that we wait for the wifi network :))

I made three reboots, got the network interface up and `ftp` connecting in every case.

Then I updated the Pi to the stored credentials again (and renamed the cfg file, just to be sure) -- worked on the first boot, didn't on second (in that case it didn't show the dialog at all).

**Comment by czietz** [comment]
> although I don't fancy yet another ALERT telling me that we wait for the wifi network

In this case I'd say that it is the same message level as with the Asix driver, where I always get _two_ alerts:
https://github.com/freemint/freemint/blob/648e0cdb2d1328927c809582822ed47a45e3b3b2/sys/sockets/xif/asix.c#L522-L530

Based on user feedback, some kind of feedback to the user is required when waiting for the link (i.e., just a DEBUG message is not sufficient), because with some Wifi routers it can take up to 30 seconds until the connection is established. Without a message, `ifconfig up` just seems frozen.

As for the problems on the CT60 when the credentials are stored in the PicoWifi: I don't have a CT60, so I'm afraid you need to debug this yourself. Sorry! Perhaps you could try just commenting out the message about trying the stored credentials and see whether that makes a difference. We know from previous investigations that FreeMiNT has some very "spooky" issues.

**Comment by mikrosk** [comment]
> In this case I'd say that it is the same message level as with the Asix driver, where I always get two alerts:

Wow, this is quite surprising. Not only I never got any ASIX alert but looking at your code, I should get also two alerts instead of one? (as the link wasn't detected at first -> alert -> timeout increased -> link detected in next iteration -> timeout != 0 -> where's the alert?)

I'll make a quick test but you are right, seeing my good old friends `(struct ueth_data *)eth->data;` and `addroottimeout` raises my eyebrows for sure.

**Comment by mikrosk** [comment]
Just to be sure, I replaced my FreeMiNT installation with the latest snapshot (incl. ifconfig and route), retaining all configuration files and scripts. (Un)fortunately, the issue is still reproducible:

- my own compiled picowifi.xif
- my own compiled picowifi.xif without the alert
- only on CT60

Symptoms were varying, from the known ones (freeze before/during the alert) to new ones, like freezing on a ftp login. Once I saw this line printed on screen: https://github.com/freemint/freemint/blob/master/sys/sockets/buf.c#L424, again only confirming that this and freemint/freemint#273 are related and something very wrong is happening in there.

**Comment by czietz** [comment]
I've downgraded the ALERT about using possibly stored Wifi credentials to a DEBUG message. See https://github.com/freemint/freemint/commit/4fef652b5b21db768b88c33c861bf908f2a5cf96.

Shall we move the more general problem you observe on the CT60 to the FreeMiNT issue tracker? Imho, this is less a PicoWifi issue but more a general (but yet not really understood) FreeMiNT issue. Furthermore, I have no idea how I could help with that.

**Comment by mikrosk** [comment]
I guess it's enough to have this mentioned in freemint/freemint#273, as it is most likely the same issue.

Perhaps the only thing you can do is to ask your beta testers whether they don't have similar setup and test it for you. I feel bad being the only one reporting this kind of crashes. I try to be very careful with setup and reproducibility so it's not some random quirk but one never knows...

Btw, didn't you want to replace `\r\n` also here: https://github.com/freemint/freemint/commit/4fef652b5b21db768b88c33c861bf908f2a5cf96#diff-d95c0a053850749caa66c6d42ab6caaf604c89a6cfdd91d483208a7209a49be8L194 ?

Anyway, I think we can consider this particular issue solved and when I find time and energy, I'll try to debug the USB crash, now that I have much more stable repro.
