### ISSUE TITLE
Lack of visible documentation

### ISSUE THREAD

**Issue by paulwalker-dev** [czietz/picowifi#3]
### What happened?

Does this project has documentation about implementing drivers anywhere. Does this project use a standard protocol?

### Firmware version

2024-01-05 1fb47ca

### Software versions on the Atari

N/a

### Hardware

Wii running NetBSD 10.0

**Comment by czietz** [comment]
There is no separate documentation about the proprietary protocol on the USB interface, since the PicoWifi project provides the firmware on the device as well as the drivers on the host (Atari) side. Hence, only the source code exists as documentation.

Summarizing it very briefly, there is one bulk-in and one bulk-out endpoint, over which the network packets are being transferred. These are Ethernet packets, wrapped in a very simple header:
https://github.com/czietz/picowifi/blob/1fb47cae39daa792808b7c9a7fa1f8adf52f4f82/picowifi.c#L48-L55

Setup is done using a handful of control transfers:
https://github.com/czietz/picowifi/blob/1fb47cae39daa792808b7c9a7fa1f8adf52f4f82/picowifi.c#L156

However, please note that I consider the USB interface an internal implementation detail, which might change in the future.

I hope this helps.
